### ISSUE TITLE
Add TS annotations

### ISSUE THREAD

**Issue by bespoyasov** [bespoyasov/scroller#27]
There is no need to re-write the whole script in TypeScript but for TypeScript support, it would be great to add `.d.ts` annotations.

**Comment by Beraliv** [comment]
I want to participate 🚀

**Comment by bespoyasov** [comment]
> I want to participate if no one is working on that 🚀

Would be awesome! ^_^

**Comment by Beraliv** [comment]
Started today a little bit

Only created constructor with config structure and went through types, where I defined every property

Will try to create PR tomorrow and will ask please to have a look at the types which need to support (because I found several of them are deprecated and I only marked them like that in JSDoc)
